# Generated by Django 4.2.3 on 2023-07-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_order_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingPrice',
            new_name='shipping',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='taxPrice',
            new_name='tax',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='total',
        ),
    ]
