from django import forms
from .models import Review
from django.forms import ModelForm

# MODELFORM EXAMPLE

class ReviewForm(ModelForm):

    # subclass required, name is specific
    class Meta:
        model = Review # REQUIRED: connects ModelForm to Model

        # fields required, points to the fields in the model
        
        # automatic
        fields = "__all__" 

        # manual
        # fields = ["first_name", "last_name", "stars"]

        # overwrites default labels generated by ModelForm
        labels = {
            "first_name": "NAME HERE",
            "last_name": "Last Name",
            "stars": "Rating"
        }

        # overwrites default errors generated by ModelForm
        error_messages = {
            "stars": {"max_value": "Rating cannot be bigger than 5", "min_value": "Rating cannot be smaller than 1"}
        }



# ===================================

# BASIC FORM EXAMPLE

# class ReviewForm(forms.Form):
#     first_name = forms.CharField(label="First Name", max_length=100)
#     last_name = forms.CharField(label="Last Name", max_length=100)
#     email = forms.EmailField(label="Email", max_length=100)

#     # the widget argument changes the type of field
#     # can also style the widget with the attrs argument
#     review = forms.CharField(label="Please write your review here", widget=forms.Textarea(attrs={"class": "form", "rows": 4, "cols": 18}))